Update process-scraped-characters.yaml

diff --git a/.github/workflows/process-scraped-characters.yaml b/.github/workflows/process-scraped-characters.yaml
--- a/.github/workflows/process-scraped-characters.yaml
+++ b/.github/workflows/process-scraped-characters.yaml
@@ -19,7 +19,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          ref: test_processor
+          ref: perchance_comments
           token: ${{ secrets.PAT_GITHUB_ACTIONS }}
           fetch-depth: 0
 
@@ -52,7 +52,7 @@ jobs:
           rm -f package-lock.json  # Remove file
           rm -f package.json
 
-      - name: Commit and push changes
+      - name: Commit and push changes to the working branch
         run: |
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
@@ -61,22 +61,38 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
 
-      - name: Fetch all branches
+      - name: Remove unwanted files from the machine to create PR
         run: |
-          git fetch origin perchance_comments
-          git fetch origin test_processor
+          rm -rf characters
+          rm -rf ai-character-char
+          rm -rf ai-character-chat/characters/scrape
+
+      - name: Create a new temporary branch from main
+        run: |
+          git fetch origin main
+          git checkout main  
+          git checkout -b processed-batch1  
+
+      - name: Commit and push changes to the new temporary branch
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add .  
+          git diff --quiet && git diff --staged --quiet || (git commit -m "Update generated files" && git push origin processed-batch1)
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
 
       - name: Create Pull Request
         env:
           GH_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
         run: |
-          if git diff --quiet origin/perchance_comments origin/test_processor; then
+          if git diff --quiet origin/main origin/processed-batch1; then
             echo "No differences found between branches. Skipping PR creation."
           else
-            gh label create "automated-pr" --color 1D76DB --description "Automatic PR generated for adding content to the DB" || echo "Label 'automated-pr' already exist or can't be created."
+            gh label create "automated-pr" --color 1D76DB --description "Automatic PR generated for adding content to the DB" || echo "Label 'automated-pr' already exists or can't be created."
             gh pr create \
-              --base perchance_comments \
-              --head test_processor \
+              --base main \
+              --head processed-batch1 \
               --title "Automated PR - Updated generated files" \
               --body "This PR contains automatically generated updates." \
               --label "automated-pr"
